syntax = "proto3";

package device_service;

service DeviceService{
  // 设备列表信息; 返回一维字符串数组
  rpc GetDeviceList (DeviceNameListRequest)returns (DeviceNameListResponse){}
  // 获得设备从机数量 ;返回单个int值
  rpc GetDeviceSlaveCnt(DeviceSlaveCntRequest)returns(DeviceSlaveCntResponse){}
  // 设备详细信息
  rpc DeviceInfo(DeviceInfoRequest) returns (DeviceInfoResponse){}
  // 根据设备名称和从机id和测点信息 获取设备详细信息,回复是二维List; 返回二维字符串数组
  rpc GetDeviceTableBySlaveId (DeviceTableBySlaveIdRequest) returns (DeviceTableBySlaveIdResponse) {}
}

message DeviceNameListRequest{
  string  device_name = 1;
}
message DeviceNameListResponse{
  repeated string device_names = 1;
}
// 获取设备从机数量
message DeviceSlaveCntRequest {
  string device_name = 1;
}

message DeviceSlaveCntResponse {
  int32 slave_cnt = 1;
}

message DeviceInfoRequest{
  // 查询的设备名称
  string device_name = 1;
}
message DeviceInfoResponse{
  DeviceInfoDetail info = 1;
}
message DeviceInfoDetail{
  string ip = 1;
  int32 port = 2;
  string type = 3;
  bool server_status = 4;
  bool simulate_status = 5;
  bool plan_status = 6;
}

message DeviceTableBySlaveIdRequest{
  string device_name = 1;
  int32 slave_id = 2;
  string point_name = 3;
}

message DeviceTableBySlaveIdResponse {
  DeviceTableRow head_data = 1;
  repeated DeviceTableRow table_data = 2;
}
message DeviceTableRow{
  repeated string row = 1;
}